name: Build Angular Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory to web
        run: cd ./web

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./web

      - name: Build Angular project
        run: npm run build --if-present
        working-directory: ./web

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: angular-build
      #     path: web/dist/
